# Tasca S12.01. APIs REST

# Nivell 1

## 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)

In [1]:
import requests
from requests.exceptions import HTTPError
import pandas as pd
import json

En primer lloc, com sempre, importem les llibreries de python

In [2]:
url1 = "https://jsonplaceholder.typicode.com/"
response_posts = requests.get(f"{url1}/posts")
response_posts.raise_for_status()
posts = response_posts.json()
print(posts)

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}, {'userId': 2, 'id': 11, 'title': 'et ea vero quia laudantium autem', 'body': 'delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi'}, {'userId': 2, 'id': 12, 'title': 'in quibusdam tempore odit est dolorem', 'body': 'itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio'}, {'userId': 2, 'id': 13, 'title': 'dolorum ut in voluptas mollitia et saepe quo animi', 'body': 'aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam'}, {'userId': 2, 'id': 14, 'title': 'voluptatem eligendi optio', 'body': 'fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum'}, {'userId': 2, 'id': 15, 'title': 'eveniet quod temporibus', 'body': 'reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae'}, {'userId': 2, 'id': 16, 'title': 'sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio', 'body': 'suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta'}, {'userId': 2, 'id': 17, 'title': 'fugit voluptas sed molestias voluptatem provident', 'body': 'eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo'}, {'userId': 2, 'id': 18, 'title': 'voluptate et itaque vero tempora molestiae', 'body': 'eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam'}, {'userId': 2, 'id': 19, 'title': 'adipisci placeat illum aut reiciendis qui', 'body': 'illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas'}, {'userId': 2, 'id': 20, 'title': 'doloribus ad provident suscipit at', 'body': 'qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo'}, {'userId': 3, 'id': 21, 'title': 'asperiores ea ipsam voluptatibus modi minima quia sint', 'body': 'repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt'}, {'userId': 3, 'id': 22, 'title': 'dolor sint quo a velit explicabo quia nam', 'body': 'eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse'}, {'userId': 3, 'id': 23, 'title': 'maxime id vitae nihil numquam', 'body': 'veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis'}, {'userId': 3, 'id': 24, 'title': 'autem hic labore sunt dolores incidunt', 'body': 'enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt'}, {'userId': 3, 'id': 25, 'title': 'rem alias distinctio quo quis', 'body': 'ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio'}, {'userId': 3, 'id': 26, 'title': 'est et quae odit qui non', 'body': 'similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero'}, {'userId': 3, 'id': 27, 'title': 'quasi id et eos tenetur aut quo autem', 'body': 'eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur'}, {'userId': 3, 'id': 28, 'title': 'delectus ullam et corporis nulla voluptas sequi', 'body': 'non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum'}, {'userId': 3, 'id': 29, 'title': 'iusto eius quod necessitatibus culpa ea', 'body': 'odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores'}, {'userId': 3, 'id': 30, 'title': 'a quo magni similique perferendis', 'body': 'alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia'}, {'userId': 4, 'id': 31, 'title': 'ullam ut quidem id aut vel consequuntur', 'body': 'debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae'}, {'userId': 4, 'id': 32, 'title': 'doloremque illum aliquid sunt', 'body': 'deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime'}, {'userId': 4, 'id': 33, 'title': 'qui explicabo molestiae dolorem', 'body': 'rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod'}, {'userId': 4, 'id': 34, 'title': 'magnam ut rerum iure', 'body': 'ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis'}, {'userId': 4, 'id': 35, 'title': 'id nihil consequatur molestias animi provident', 'body': 'nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit'}, {'userId': 4, 'id': 36, 'title': 'fuga nam accusamus voluptas reiciendis itaque', 'body': 'ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore'}, {'userId': 4, 'id': 37, 'title': 'provident vel ut sit ratione est', 'body': 'debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui'}, {'userId': 4, 'id': 38, 'title': 'explicabo et eos deleniti nostrum ab id repellendus', 'body': 'animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure'}, {'userId': 4, 'id': 39, 'title': 'eos dolorem iste accusantium est eaque quam', 'body': 'corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex'}, {'userId': 4, 'id': 40, 'title': 'enim quo cumque', 'body': 'ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam'}, {'userId': 5, 'id': 41, 'title': 'non est facere', 'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'}, {'userId': 5, 'id': 42, 'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas', 'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'}, {'userId': 5, 'id': 43, 'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis', 'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'}, {'userId': 5, 'id': 44, 'title': 'optio dolor molestias sit', 'body': 'temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae'}, {'userId': 5, 'id': 45, 'title': 'ut numquam possimus omnis eius suscipit laudantium iure', 'body': 'est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem'}, {'userId': 5, 'id': 46, 'title': 'aut quo modi neque nostrum ducimus', 'body': 'voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid'}, {'userId': 5, 'id': 47, 'title': 'quibusdam cumque rem aut deserunt', 'body': 'voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate'}, {'userId': 5, 'id': 48, 'title': 'ut voluptatem illum ea doloribus itaque eos', 'body': 'voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit'}, {'userId': 5, 'id': 49, 'title': 'laborum non sunt aut ut assumenda perspiciatis voluptas', 'body': 'inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut'}, {'userId': 5, 'id': 50, 'title': 'repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem', 'body': 'error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur'}, {'userId': 6, 'id': 51, 'title': 'soluta aliquam aperiam consequatur illo quis voluptas', 'body': 'sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem'}, {'userId': 6, 'id': 52, 'title': 'qui enim et consequuntur quia animi quis voluptate quibusdam', 'body': 'iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum'}, {'userId': 6, 'id': 53, 'title': 'ut quo aut ducimus alias', 'body': 'minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique'}, {'userId': 6, 'id': 54, 'title': 'sit asperiores ipsam eveniet odio non quia', 'body': 'totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia'}, {'userId': 6, 'id': 55, 'title': 'sit vel voluptatem et non libero', 'body': 'debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit'}, {'userId': 6, 'id': 56, 'title': 'qui et at rerum necessitatibus', 'body': 'aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi'}, {'userId': 6, 'id': 57, 'title': 'sed ab est est', 'body': 'at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est'}, {'userId': 6, 'id': 58, 'title': 'voluptatum itaque dolores nisi et quasi', 'body': 'veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam'}, {'userId': 6, 'id': 59, 'title': 'qui commodi dolor at maiores et quis id accusantium', 'body': 'perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt'}, {'userId': 6, 'id': 60, 'title': 'consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere', 'body': 'asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis'}, {'userId': 7, 'id': 61, 'title': 'voluptatem doloribus consectetur est ut ducimus', 'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'}, {'userId': 7, 'id': 62, 'title': 'beatae enim quia vel', 'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'}, {'userId': 7, 'id': 63, 'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit', 'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'}, {'userId': 7, 'id': 64, 'title': 'et fugit quas eum in in aperiam quod', 'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui'}, {'userId': 7, 'id': 65, 'title': 'consequatur id enim sunt et et', 'body': 'voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur'}, {'userId': 7, 'id': 66, 'title': 'repudiandae ea animi iusto', 'body': 'officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe'}, {'userId': 7, 'id': 67, 'title': 'aliquid eos sed fuga est maxime repellendus', 'body': 'reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae'}, {'userId': 7, 'id': 68, 'title': 'odio quis facere architecto reiciendis optio', 'body': 'magnam molestiae perferendis quisquam\nqui cum reiciendis\nquaerat animi amet hic inventore\nea quia deleniti quidem saepe porro velit'}, {'userId': 7, 'id': 69, 'title': 'fugiat quod pariatur odit minima', 'body': 'officiis error culpa consequatur modi asperiores et\ndolorum assumenda voluptas et vel qui aut vel rerum\nvoluptatum quisquam perspiciatis quia rerum consequatur totam quas\nsequi commodi repudiandae asperiores et saepe a'}, {'userId': 7, 'id': 70, 'title': 'voluptatem laborum magni', 'body': 'sunt repellendus quae\nest asperiores aut deleniti esse accusamus repellendus quia aut\nquia dolorem unde\neum tempora esse dolore'}, {'userId': 8, 'id': 71, 'title': 'et iusto veniam et illum aut fuga', 'body': 'occaecati a doloribus\niste saepe consectetur placeat eum voluptate dolorem et\nqui quo quia voluptas\nrerum ut id enim velit est perferendis'}, {'userId': 8, 'id': 72, 'title': 'sint hic doloribus consequatur eos non id', 'body': 'quam occaecati qui deleniti consectetur\nconsequatur aut facere quas exercitationem aliquam hic voluptas\nneque id sunt ut aut accusamus\nsunt consectetur expedita inventore velit'}, {'userId': 8, 'id': 73, 'title': 'consequuntur deleniti eos quia temporibus ab aliquid at', 'body': 'voluptatem cumque tenetur consequatur expedita ipsum nemo quia explicabo\naut eum minima consequatur\ntempore cumque quae est et\net in consequuntur voluptatem voluptates aut'}, {'userId': 8, 'id': 74, 'title': 'enim unde ratione doloribus quas enim ut sit sapiente', 'body': 'odit qui et et necessitatibus sint veniam\nmollitia amet doloremque molestiae commodi similique magnam et quam\nblanditiis est itaque\nquo et tenetur ratione occaecati molestiae tempora'}, {'userId': 8, 'id': 75, 'title': 'dignissimos eum dolor ut enim et delectus in', 'body': 'commodi non non omnis et voluptas sit\nautem aut nobis magnam et sapiente voluptatem\net laborum repellat qui delectus facilis temporibus\nrerum amet et nemo voluptate expedita adipisci error dolorem'}, {'userId': 8, 'id': 76, 'title': 'doloremque officiis ad et non perferendis', 'body': 'ut animi facere\ntotam iusto tempore\nmolestiae eum aut et dolorem aperiam\nquaerat recusandae totam odio'}, {'userId': 8, 'id': 77, 'title': 'necessitatibus quasi exercitationem odio', 'body': 'modi ut in nulla repudiandae dolorum nostrum eos\naut consequatur omnis\nut incidunt est omnis iste et quam\nvoluptates sapiente aliquam asperiores nobis amet corrupti repudiandae provident'}, {'userId': 8, 'id': 78, 'title': 'quam voluptatibus rerum veritatis', 'body': 'nobis facilis odit tempore cupiditate quia\nassumenda doloribus rerum qui ea\nillum et qui totam\naut veniam repellendus'}, {'userId': 8, 'id': 79, 'title': 'pariatur consequatur quia magnam autem omnis non amet', 'body': 'libero accusantium et et facere incidunt sit dolorem\nnon excep

Probem que la conexió amb la url sigui correcte. I covertim el resultat de GET a json, per a mostrar-lo com a llista. 
Malgrat que l'exercisi no ho demana, imprimim els resultats per fer un primer cop d'ull a les dades adquirides amb JSON

In [3]:
response_users = requests.get(f"{url1}/users")
response_users.raise_for_status()
users= response_users.json()
print(users)
response_tasques = requests.get(f"{url1}/todos")
response_tasques.raise_for_status()
tasques = response_tasques.json()
print(tasques)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

Repetim el procés, aquest cop amb els usuaris i les tasques, canviant el parametre d'obtenció.

## 2. Mostra per pantalla:

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [4]:
print("La quantitat del recurs posts es de", len(posts))
print("El codi d'estat per a users es", response_posts.status_code)
print("La quantitat del recurs users es de", len(users))
print("El codi d'estat per a posts es", response_users.status_code)
print("La quantitat del recurs tasques es de", len(tasques))
print("El codi d'estat per a tasques es", response_tasques.status_code)

La quantitat del recurs posts es de 100
El codi d'estat per a users es 200
La quantitat del recurs users es de 10
El codi d'estat per a posts es 200
La quantitat del recurs tasques es de 200
El codi d'estat per a tasques es 200

Amb len() obtenim la quantitat total d'elements de cada recurs. Amb status_code accedim al codi d'estat de les peticions.

## 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [5]:
response_error = requests.get(f"{url1}/patates")
try:
    response_error.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

Error HTTP: 404 Client Error: Not Found for url: https://jsonplaceholder.typicode.com//patates

Fem de nou la petició amb una URL inventada per a obtenir l'error, amb un control Try/except per que ens retorni l'error de manera controlada i llegible.

## 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [6]:
peticio_post = {'userId': "BBB", 
                'title': 'Un post de prova', 
                'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs\nBarcelona Activa'}

response_post = requests.post(f"{url1}/posts", json = peticio_post)
try:
    response_post.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

post = response_post.json()
print(post)

print("El estat de la petició es", response_post.status_code)

{'userId': 'BBB', 'title': 'Un post de prova', 'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs\nBarcelona Activa', 'id': 101}
El estat de la petició es 201

Llencem la petició per afegir noves dades amb post, i aprofitem el codi per al control d'errors. La importació és correcta i podem veure les dades en forma de diccionari. Observem que ha assignat una id 101 (el maxim que ja existia +1). El valor de codi de estat 201 confirma que la operació s'ha fet correctament.

## 5. Fes una petició PATCH per modificar parcialment una publicació existent.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [7]:
peticio_patch = {'userId': "BBB", 
                'title': 'Un post de prova modificat', 
                'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs 2026\nBarcelona Activa'}

response_patch = requests.patch(f"{url1}/posts/101", json = peticio_patch)
try:
    response_patch.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

patch = response_post.json()
print(patch)

print("El estat de la petició es", response_patch.status_code)

{'userId': 'BBB', 'title': 'Un post de prova', 'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs\nBarcelona Activa', 'id': 101}
El estat de la petició es 200

In [8]:
peticio_patch = {'userId': "BBB", 
                'title': 'Un post de prova modificat', 
                'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs 2026\nBarcelona Activa'}

response_patch = requests.patch(f"{url1}/posts/1", json = peticio_patch)
try:
    response_patch.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

patch = response_patch.json()
print(patch)

print("El estat de la petició es", response_patch.status_code)

{'userId': 'BBB', 'id': 1, 'title': 'Un post de prova modificat', 'body': 'Aquest és un post de prova\nPertany al exercisi 4 del nivell 1\nIT Academy - Data Analitycs 2026\nBarcelona Activa'}
El estat de la petició es 200

Primer, hem intentat modificar el post fictici creat en l'exercisi anterior. Però JSONplaceholder només simula la creació d'un nou recurs, i no l'hem pogut modificar, tot i no retornar error. 

A continuació, repetim la petició patch, aquest cop amb l'objectiu de modificar el post el recurs /posts/1. En aquest cas, si retorna una resposta simulada on s'han modificat les dades (com a mínim aparentment).

## 6. Fes una petició DELETE sobre una publicació.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [9]:
response_delete = requests.delete(f"{url1}/posts/1")
try:
    response_delete.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

delete = response_delete.json()
print(delete)

print("El estat de la petició es", response_delete.status_code)

{}
El estat de la petició es 200

En aquest cas fem la petició DELETE sobre el mateix conjunt de dades.

La resposta JSON és un diccionari buit {}, i el codi d’estat és 200 OK, indicant que la petició s’ha processat correctament, encara que no s’hagi eliminat cap dada real.

# Nivell 2

Interacció amb una API pública real
## 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

In [10]:
swapi = "https://www.swapi.tech/api/"
response_swapi = requests.get(f"{swapi}")
try:
    response_swapi.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")
swapi_json = response_swapi.json()
print(swapi_json)

{'message': 'ok', 'result': {'films': 'https://www.swapi.tech/api/films', 'people': 'https://www.swapi.tech/api/people', 'planets': 'https://www.swapi.tech/api/planets', 'species': 'https://www.swapi.tech/api/species', 'starships': 'https://www.swapi.tech/api/starships', 'vehicles': 'https://www.swapi.tech/api/vehicles'}, 'apiVersion': '1.0', 'timestamp': '2026-05-24T10:28:38.744Z', 'support': {'contact': 'admin@swapi.tech', 'donate': 'https://www.paypal.com/donate/?business=2HGAUVTWGR5T2&no_recurring=0&item_name=Support+Swapi+and+keep+the+galaxy%27s+data+free%21+Your+donation+fuels+open-source+innovation+and+helps+us+grow.+Thank+you%21+%F0%9F%9A%80&currency_code=USD', 'partnerDiscounts': {'saberMasters': {'link': 'https://www.swapi.tech/partner-discount/sabermasters-swapi', 'details': 'Use this link to automatically get $10 off your purchase!'}, 'heartMath': {'link': 'https://www.heartmath.com/ryanc', 'details': 'Looking for some Jedi-like inner peace? Take 10% off your heart-brain coherence tools from the HeartMath Institute!'}}}, 'social': {'discord': 'https://discord.gg/zWvA6GPeNG', 'reddit': 'https://www.reddit.com/r/SwapiOfficial/', 'github': 'https://github.com/semperry/swapi/blob/main/CONTRIBUTORS.md'}}

Escollim https://www.swapi.tech/ (base de dades de l'univers Star Wars) com a objectiu de les nostres peticions. La petició GET sobre l'identificador /films ens retorna un llistat de les diferents seccións que integren la base de dades:

## 2. Llegeix la documentació de l'API:

### Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.

Prendrem dos endpoint dels 6 que ens ofereix aquesta API:
    - /starships → https://www.swapi.tech/api/starships
    - /vehicles → https://www.swapi.tech/api/vehicles

### Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.

In [42]:
response_swapi = requests.get(f"{swapi}/starships")
try:
    response_swapi.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")
swapi_json = response_swapi.json()
print(swapi_json)

{'message': 'ok', 'total_records': 36, 'total_pages': 4, 'previous': None, 'next': 'https://www.swapi.tech/api/starships?page=2&limit=10', 'results': [{'uid': '2', 'name': 'CR90 corvette', 'url': 'https://www.swapi.tech/api/starships/2'}, {'uid': '3', 'name': 'Star Destroyer', 'url': 'https://www.swapi.tech/api/starships/3'}, {'uid': '5', 'name': 'Sentinel-class landing craft', 'url': 'https://www.swapi.tech/api/starships/5'}, {'uid': '9', 'name': 'Death Star', 'url': 'https://www.swapi.tech/api/starships/9'}, {'uid': '11', 'name': 'Y-wing', 'url': 'https://www.swapi.tech/api/starships/11'}, {'uid': '10', 'name': 'Millennium Falcon', 'url': 'https://www.swapi.tech/api/starships/10'}, {'uid': '13', 'name': 'TIE Advanced x1', 'url': 'https://www.swapi.tech/api/starships/13'}, {'uid': '15', 'name': 'Executor', 'url': 'https://www.swapi.tech/api/starships/15'}, {'uid': '12', 'name': 'X-wing', 'url': 'https://www.swapi.tech/api/starships/12'}, {'uid': '17', 'name': 'Rebel transport', 'url': 'https://www.swapi.tech/api/starships/17'}], 'apiVersion': '1.0', 'timestamp': '2026-05-24T11:13:00.024Z', 'support': {'contact': 'admin@swapi.tech', 'donate': 'https://www.paypal.com/donate/?business=2HGAUVTWGR5T2&no_recurring=0&item_name=Support+Swapi+and+keep+the+galaxy%27s+data+free%21+Your+donation+fuels+open-source+innovation+and+helps+us+grow.+Thank+you%21+%F0%9F%9A%80&currency_code=USD', 'partnerDiscounts': {'saberMasters': {'link': 'https://www.swapi.tech/partner-discount/sabermasters-swapi', 'details': 'Use this link to automatically get $10 off your purchase!'}, 'heartMath': {'link': 'https://www.heartmath.com/ryanc', 'details': 'Looking for some Jedi-like inner peace? Take 10% off your heart-brain coherence tools from the HeartMath Institute!'}}}, 'social': {'discord': 'https://discord.gg/zWvA6GPeNG', 'reddit': 'https://www.reddit.com/r/SwapiOfficial/', 'github': 'https://github.com/semperry/swapi/blob/main/CONTRIBUTORS.md'}}

Podem consultar els paràmetres disponibles a la documentació oficial de l'API:

https://www.swapi.tech/documentation#params

A la documentació veiem uns paràmetres generals i atributs que es poden aplicar a cada col·lecció, com per exemple "?page=" per a navegar entre els resultats, !?limit=" per limitar el nombre de resultats retornat iparàmetres especifics per a filtrar atributs concrets com "/people?name=", que ens permet buscar per nom, en el cas dels personatges:

https://www.swapi.tech/api/people?page=2

https://www.swapi.tech/api/planets?limit=5

https://www.swapi.tech/api/people?name=skywalker

### Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici)

In [43]:
response = requests.get(f"{swapi}/starships?name=falcon")
print(response.headers["Content-Type"])

application/json; charset=utf-8

Per a verificar el format de sortida del retorn de dades es JSON, fem una petició GET a un dels endpoint, revisant els headers amb ["content_Type"]. La base de la URL "https://www.swapi.tech/api/" retorna HTLM perque es una pàgina informativa, pero els endpoint de dades si que son JSON.

## 3. Fes una petició GET senzilla:

### Mostra el codi d'estat de la resposta.

In [44]:
response_falcon = requests.get(f"{swapi}/starships?name=falcon")
try:
    response_falcon.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

data = response_falcon.json()
print(data)

print("El estat de la petició es", response_falcon.status_code)

{'message': 'ok', 'result': [{'properties': {'created': '2026-05-23T19:51:37.622Z', 'edited': '2026-05-23T19:51:37.622Z', 'consumables': '2 months', 'name': 'Millennium Falcon', 'cargo_capacity': '100000', 'passengers': '6', 'max_atmosphering_speed': '1050', 'crew': '4', 'length': '34.37', 'model': 'YT-1300 light freighter', 'cost_in_credits': '100000', 'manufacturer': 'Corellian Engineering Corporation', 'pilots': ['https://www.swapi.tech/api/people/13', 'https://www.swapi.tech/api/people/14', 'https://www.swapi.tech/api/people/25', 'https://www.swapi.tech/api/people/31'], 'MGLT': '75', 'starship_class': 'Light freighter', 'hyperdrive_rating': '0.5', 'films': ['https://www.swapi.tech/api/films/1', 'https://www.swapi.tech/api/films/2', 'https://www.swapi.tech/api/films/3'], 'url': 'https://www.swapi.tech/api/starships/10'}, '_id': '5f63a34fee9fd7000499be23', 'description': 'A Starship', 'uid': '10', '__v': 2}], 'apiVersion': '1.0', 'timestamp': '2026-05-24T11:13:08.470Z', 'support': {'contact': 'admin@swapi.tech', 'donate': 'https://www.paypal.com/donate/?business=2HGAUVTWGR5T2&no_recurring=0&item_name=Support+Swapi+and+keep+the+galaxy%27s+data+free%21+Your+donation+fuels+open-source+innovation+and+helps+us+grow.+Thank+you%21+%F0%9F%9A%80&currency_code=USD', 'partnerDiscounts': {'saberMasters': {'link': 'https://www.swapi.tech/partner-discount/sabermasters-swapi', 'details': 'Use this link to automatically get $10 off your purchase!'}, 'heartMath': {'link': 'https://www.heartmath.com/ryanc', 'details': 'Looking for some Jedi-like inner peace? Take 10% off your heart-brain coherence tools from the HeartMath Institute!'}}}, 'social': {'discord': 'https://discord.gg/zWvA6GPeNG', 'reddit': 'https://www.reddit.com/r/SwapiOfficial/', 'github': 'https://github.com/semperry/swapi/blob/main/CONTRIBUTORS.md'}}
El estat de la petició es 200

### Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [46]:
falcon_url = "https://www.swapi.tech/api/starships/10"
response_falcon = requests.get(falcon_url)
try:
    response_falcon.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

falcon = response_falcon.json()
falcon = falcon['result']['properties']
print(falcon)

print("El estat de la petició es", response_falcon.status_code)


print("\n"+f'El fabricant de {falcon["name"]} és {falcon["manufacturer"]}')
print(f'El model és {falcon["model"]},')
print(f'Apareix en {len(falcon["films"])} pelicules de la saga')

{'created': '2026-05-23T19:51:37.622Z', 'edited': '2026-05-23T19:51:37.622Z', 'consumables': '2 months', 'name': 'Millennium Falcon', 'cargo_capacity': '100000', 'passengers': '6', 'max_atmosphering_speed': '1050', 'crew': '4', 'length': '34.37', 'model': 'YT-1300 light freighter', 'cost_in_credits': '100000', 'manufacturer': 'Corellian Engineering Corporation', 'pilots': ['https://www.swapi.tech/api/people/13', 'https://www.swapi.tech/api/people/14', 'https://www.swapi.tech/api/people/25', 'https://www.swapi.tech/api/people/31'], 'MGLT': '75', 'starship_class': 'Light freighter', 'hyperdrive_rating': '0.5', 'films': ['https://www.swapi.tech/api/films/1', 'https://www.swapi.tech/api/films/2', 'https://www.swapi.tech/api/films/3'], 'url': 'https://www.swapi.tech/api/starships/10'}
El estat de la petició es 200

El fabricant de Millennium Falcon és Corellian Engineering Corporation
El model és YT-1300 light freighter,
Apareix en 3 pelicules de la saga

Per a accedir a les caraterìstique en especific de l'item cercat, hem de feu una nova petició GET a l'URL que ens ha mostrat el resultat de la cerca de l'apartat anterior. Així, ja podrem accedir als valors de cada característica, a través de les seves claus.

## 4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [47]:
df_falcon = pd.DataFrame([falcon])
df_falcon

,created,edited,consumables,name,cargo_capacity,passengers,max_atmosphering_speed,crew,length,model,cost_in_credits,manufacturer,pilots,MGLT,starship_class,hyperdrive_rating,films,url
0,2026-05-23T19:51:37.622Z,2026-05-23T19:51:37.622Z,2 months,Millennium Falcon,100000,6,1050,4,34.37,YT-1300 light freighter,100000,Corellian Engineering Corporation,"[https://www.swapi.tech/api/people/13, https:/...",75,Light freighter,0.5,"[https://www.swapi.tech/api/films/1, https://w...",https://www.swapi.tech/api/starships/10

Per a convertir el resultat de la cerca en un DataFrame, hem de passar el valor entre "[]", per convertirlo a un diccionari que agafa la forma de DataFrame d'una sola columna. Sense això, la diferent longituts dels arrays dels resultats, no permeten la conversió.

# Nivell 3

## 1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show.

In [16]:
bcn_od_url = "https://opendata-ajuntament.barcelona.cat/data/api/action/"
response_bcn = requests.get(f"{bcn_od_url}//package_list")
try:
    response_bcn.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

bcn_data_list = response_bcn.json()

bcn_data_list["result"]

['20170706-districtes-barris',
 'accessibilitat-via-publica',
 'accidents_causa_conductor_gu_bcn',
 'accidents-causes-gu-bcn',
 'accidents-gu-bcn',
 'accidents-persones-gu-bcn',
 'accidents-tipus-gu-bcn',
 'accidents-vehicles-gu-bcn',
 'accions-formatives-adrecades-al-personal',
 'acollida-animals',
 'administracio-autonomica',
 'administracio-estatal',
 'administracio-municipal',
 'afectacions-turistiques',
 'afectacions-turistiques-a-espais-verds',
 'aforaments-descriptiu',
 'aforaments-detall',
 'aforament-tipus-equipament',
 'agenda-activitats-esportives',
 'agenda-cultural',
 'agenda-diaria',
 'agenda-publica-alcaldesa',
 'agendes-publiques-comissionats',
 'agendes-publiques-regidors',
 'alcaldes-alcaldesses-bcn',
 'allotjaments-altres',
 'allotjaments-hotels',
 'allotjaments-pensions',
 'ampliacio-voreres-bici-bcn',
 'aparcaments-bcn',
 'aparcaments-servei-bicis',
 'aparcaments-sota-superficie',
 'arbrat-parcs',
 'arbrat-viari',
 'arbrat-zona',
 'arbres-interes-local',
 'arees-esbarjo-gossos-bcn',
 'atles-biodiversitat-arbrat-especies',
 'atles-biodiversitat-arbrat-geometries',
 'atles-biodiversitat-arbrat-rel-geometria-especie',
 'atles-biodiversitat-flora-especies',
 'atles-biodiversitat-flora-geometries',
 'atles-biodiversitat-flora-rel-geometria-especie',
 'atles-renda-bruta-per-llar',
 'atles-renda-bruta-per-persona',
 'atles-renda-index-gini',
 'atles-renda-mediana',
 'atles-renda-mitjana',
 'atles-renda-p80-p20-distribucio',
 'autenticacions-punts-recarrega-electric',
 'aut-terrasses-excep-decret-21-5',
 'bancs-del-temps-bcn',
 'barcelona-activa-projectes',
 'benzineres',
 'biblioteca_arus_bcnroc',
 'bicicletes',
 'bicing',
 'calendari-festes-laborals',
 'campanyes-publicitat-institucional',
 'capacitat-mapa-estrategic-soroll',
 'carrecs-electes-comissionats-i-gerents',
 'carrerer',
 'carrers-30-bcn',
 'carrers-pacificats-bici-bcn',
 'carrers-plataforma-unica-bcn',
 'carrers-vianants-bcn',
 'carril-bici',
 'carrils-bici-en-construccio',
 'carrils-bici-municipis',
 'carta-arqueologica-barcelona',
 'cataleg-bases-ajuts-subvencions-bcnroc',
 'cataleg-bases-us-espai-public-bcnroc',
 'cataleg-bcnroc',
 'cataleg-cartes-de-serveis-i-politiques-de-qualitat-bcnroc',
 'cataleg-cartobcn',
 'cataleg-circulars-bcnroc',
 'cataleg-comptes-bcnroc',
 'cataleg-costos-bcnroc',
 'cataleg-declaracions-institucionals-bcnroc',
 'cataleg-decrets-alcaldia-bcnroc',
 'cataleg-dictamens-bcnroc',
 'cataleg-directrius-bcnroc',
 'cataleg-documents-alcaldes-bcnroc',
 'cataleg-documents-tecnics-bcnroc',
 'cataleg-dossiers-notes-premsa-bcnroc',
 'cataleg-enquestes-bcnroc',
 'cataleg-estatuts-bcnroc',
 'cataleg-fotografies-art-public-bcnroc',
 'cataleg-fotografies-barcelona-general-bcnroc',
 'cataleg-fotografies-cementiris-bcnroc',
 'cataleg-fotografies-edificis-bcnroc',
 'cataleg-fotografies-elements-urbans-bcnroc',
 'cataleg-fotografies-projectes-urbans-bcnroc',
 'cataleg_fotografies_temes_bcnroc',
 'cataleg-havana-bcnroc',
 'cataleg-informes-avaluacio-bcnroc',
 'cataleg-informes-diversos-bcnroc',
 'cataleg-informes-organs-govern-bcnroc',
 'cataleg-instruccions-bcnroc',
 'cataleg-laudes-bcnroc',
 'cataleg-memories-bcnroc',
 'cataleg-mesures-govern-bcnroc',
 'cataleg-opendata',
 'cataleg-ordenances-fiscals-preus-bcnroc',
 'cataleg-ordenances-municipals-bcnroc',
 'cataleg-plans-especials-bcnroc',
 'cataleg-plans-estrategics-bcnroc',
 'cataleg-premis-bcnroc',
 'cataleg-pressupostos-bcnroc',
 'cataleg-protocols-bcnroc',
 'cataleg-publicacions-bcnroc',
 'cataleg-reglaments-bcnroc',
 'cataleg-rei-bcnroc',
 'cataleg-revistes-bcnroc',
 'cementiris',
 'cens-activitats-economiques-class-bcn',
 'cens-animals-companyia',
 'cens-locals-planta-baixa-act-economica',
 'centres-civics-activitatsdifusio',
 'centres-civics-entitats',
 'centres-civics-formacio',
 'centres-civics-metres-quadrats',
 'cinemes-dades-globals',
 'cobertura-vegetal-ndvi',
 'cohesio-social',
 'colors-aparcaments-superficie',
 'comissaries-policia',
 'compatibilitats',
 'compliment-objectius-estabilitat',
 'comportament-energetic-edificis',
 'confort-termic',
 'consolats-bcn',
 'consum-aigua',
 'consum-electricitat-bcn',
 'contaminacio-atmosferica',
 'contaminants-estacions-mesura-qualitat-aire',
 'contractes-menors',
 'contractes-menors-a-generica',
 'corredors-bici-bcn',
 'culturailleure-bibliotequesimuseus',
 'culturailleure-cinemesteatresauditoris',
 'culturailleure-espaisinfantils',
 'culturailleure-espaismusicacopes',
 'culturailleure-espaisparticipaciociutadana',
 'culturailleure-parcsjardins',
 'dades-arts-esceniques',
 'dades-arxius',
 'dades-ateneus',
 'dades-festes-ciutat',
 'dades-festival-grec',
 'dades-festivals',
 'dades-globals-cultura',
 'dades-grans-auditoris',
 'dades-merce',
 'dades-museus-exposicions',
 'dades-projectes-fabriques-creacio',
 'dades-sales-musica-viu-agrup-dimensions',
 'dades-sindicals',
 'dades-xarxa-biblioteques-catalunya',
 'deficit-proximitat-espai-verd',
 'densitat-activitats',
 'densitat-huts',
 'denuncies_sancions_transit_bcn_codis',
 'denuncies_sancions_transit_bcn_conceptes_annex',
 'denuncies_sancions_transit_bcn_detall',
 'denuncies_sancions_transit_bcn_tip_vehicle',
 'dutxes-platges',
 'ebsib-bcn-enquesta-benestar-subjectiu-infancia',
 'edificis-amics-de-la-bici-barcelona',
 'educacio-ensenyament-infantil',
 'educacio-ensenyament-no-reglat',
 'educacio-ensenyament-reglat',
 'enquesta-escletxa-digital',
 'entitas-pacte-mobilitat',
 'entitats',
 'entitats-municipals',
 'equipament-administracio',
 'equipament-animals-i-plantes',
 'equipament-associacions',
 'equipament-cementiris-i-serveis-relacionats',
 'equipament-centres-d-informacio',
 'equipament-companyies-de-serveis',
 'equipament-cultura-i-lleure',
 'equipament-educacio',
 'equipament-esports',
 'equipament-medi-ambient-i-serveis-relacionats',
 'equipament-mercats-i-centres-comercials',
 'equipament-mitjans-de-comunicacio-i-serveis-relacionats',
 'equipament-restaurants',
 'equipament-sanitat',
 'equipaments-culturals-icub',
 'equipament-serveis-religiosos',
 'equipament-serveis-socials',
 'equipaments-i-parcs-refugi',
 'equipaments-relacionats-amb-transports',
 'equipament-transports-i-serveis-relacionats',
 'escales-mecaniques',
 'esm-bcn-evo',
 'espais-creacio-activitats-difusio',
 'espais-creacio-formacio-professionals',
 'espais-creacio-metres-quadrats',
 'espais-prioritaris-neteja-barcelona',
 'espais-verds-publics',
 'esports-equip',
 'esports-individuals',
 'esports-instal-lacions-esportives',
 'estacionaments-dum',
 'estacions-bus',
 'estacions-maritimes',
 'estat-estacions-bicing',
 'estat-ports-recarrega-electric',
 'est-cadastre-carrecs-quota-cadastral',
 'est-cadastre-carrecs-tipus-propietari',
 'est-cadastre-carrecs-us',
 'est-cadastre-carrecs-valors-cadastrals',
 'est-cadastre-edificacions-any-const',
 'est-cadastre-edificacions-edat-mitjana',
 'est-cadastre-edificacions-nombre-locals',
 'est-cadastre-edificacions-superficie',
 'est-cadastre-finques-regim-propietat',
 'est-cadastre-finques-superficie',
 'est-cadastre-habitatges-any-const',
 'est-cadastre-habitatges-edat-mitjana',
 'est-cadastre-habitatges-propietari',
 'est-cadastre-habitatges-superficie',
 'est-cadastre-habitatges-superficie-mitjana',
 'est-cadastre-habitatges-valor-cadastral',
 'est-cadastre-locals-prop',
 'est-cadastre-locals-sup',
 'est-cadastre-locals-us-desti',
 'est-cadastre-locals-valors-total-unitaris',
 'est-demo-taxa-migracio-interna',
 'est-densitat',
 'est-eleccions-autonomiques-seccio-censal',
 'est-eleccions-europees-seccio-censal',
 'est-eleccions-generals-seccio-censal',
 'est-eleccions-locals-seccio-censal',
 'est-social-discapacitats-grau',
 'est-social-discapacitats-grups-edat',
 'est-social-discapacitats-sexe',
 'est-social-discapacitats-tipus',
 'est-superficie',
 'est-vehicles-amb-distintiu',
 'est-vehicles-antiguitat-menys-un-any',
 'est-vehicles-antiguitat-motos',
 'est-vehicles-antiguitat-tipus',
 'est-vehicles-antiguitat-turismes',
 'est-vehicles-cilindrada-motos',
 'est_vehicles_evolucio_total',
 'est_vehicles_index_motor',
 'est-vehicles-nacionalitat-propietari',
 'est-vehicles-nacionalitat-propietari-motos',
 'est-vehicles-potencia-fiscal-turismes',
 'est_vehicles_propulsio',
 'est_vehicles_servei',
 'est-vehicles-tipologia-parc-vehicles',
 'est-vehicles-tipus-propietari',
 'est-vehicles-tipus-propietari-motos',
 'evolucio-despeses-corrents-per-politiques',
 'evolucio-despeses-per-capitols',
 'evolucio-despeses-per-capitols-i-articles',
 'evolucio-despeses-per-unitats-organiques',
 'evolucio-deute',
 'evolucio-ingressos-per-capitols',
 'evolucio-ingressos-per-capitols-i-articles',
 'evolucio-resultat-ingressos-i-despeses',
 'exclusio-residencial',
 'facanes-mapa-estrategic-soroll',
 'factor-de-vulnerabilitat',
 'fitxer_entitats',
 'fitxes-ocupacionals',
 'fonts',
 'fonts-ornamentals',
 'formacio-poblacio-insuficient',
 'frase',
 'funiculars',
 'galeries-comercials',
 'grans-centres-comercials',
 'grans-establiments',
 'gruamunicipalbcn-retirada-codis',
 'gruamunicipalbcn-retirada-diposits',
 'gruamunicipalbcn-retiradavehicles',
 'h2mave-anualt1b',
 'h2mave-anualt2b',
 'h2mave-anualt3b',
 'h2mave-semestralt1b',
 'h2mave-semestralt2b',
 'h2mave-semestralt3b',
 'h2mave-totalt1b',
 'h2mave-totalt2b',
 'h2mave-totalt3b',
 'h2mave-totalt4b',
 'h2mave-totalt5b',
 'habitatges-2na-ma',
 'habitatges-us-turistic',
 'habit-fam-dest-habit-segons-any-const',
 'habit-fam-sit-edif-dest-habit-segons-tip',
 'habit-ppal-segons-any-const',
 'habit-ppal-segons-estat-conserv-edif',
 'habit-ppal-segons-instal1-calef',
 'habit-ppal-segons-instal2-aigua',
 'habit-ppal-segons-instal3-telf-i-int',
 'habit-ppal-segons-nombre-pers-viuen',
 'habit-ppal-segons-nom-habit',
 'habit-ppal-segons-regim-tin',
 'habit-ppal-segons-sup-util',
 'horaris-aparcaments-superficie',
 'horts-urbans',
 'immobles-quotes-padro-ibi',
 'immo-edif-hab-segons-any-construccio',
 'immo-edif-hab-segons-estat-conservacio',
 'immo-edif-hab-segons-instalacions',
 'immo-edif-hab-segons-num-plantes-sobre-rasant',
 'immo-edif-hab-segons-num-plantes-sota-rasant',
 'impacte-de-la-calor',
 'incidents-gestionats-gub',
 'indicadors-transparencia-pressupostaria',
 'informacio-estacions-bicing',
 'informacio-punts-recarrega-electric',
 'informacio-rutes-autobus-estacio-del-nord',
 'infraestructures-inventari-bancs',
 'infraestructures-inventari-cameres',
 'infraestructures-inventari-inscripcions',
 'infraestructures-inventari-pas-vianants',
 'infraestructures-inventari-pilones',
 'infraestructures-inventari-reductors-velocitat',
 'infraestructures-inventari-reserves',
 'infraestructures-inventari-semafors',
 'infraestructures-inventari-senyalitzacio',
 'infraestructures-inventari-senyals',
 'infraestructures-inventari-separa-carrils-bici',
 'infraestructures-inventari-suports',
 'infraestructures-tipologia-inscripcions',
 'infraestructures-tipologia-pas-vianants',
 'infraestructures-tipologia-semafors',
 'infraestructures-tipologia-senyals',
 'infraestructures-tipologia-suports-cameres',
 'intensitat-activitat-turistica',
 'iris',
 'isofones-mapa-estrategic-soroll',
 'itineraris',
 'laterals-tallats-transit-bici-bcn',
 'lavabos-publics',
 'limits-municipals-districtes',
 'llista-exposicions-temporals',
 'llocs-culte',
 'lloguer-de-vehicles',
 'locve-evolucio',
 'manteniment-lloguer',
 'mapa-acustic-wms',
 'mapa-ambits-urbanistics-wms',
 'mapa-base-de-vialitat',
 'mapa-base-guia',
 'mapa-base-topografic',
 'mapa-construccions-poblament-wms',
 'mapa-de-la-malla-de-fulls-utm',
 'mapa-de-retolacio-de-carrers',
 'mapa-energia-teleco-wms',
 'mapa-graf-viari-carrers-wms',
 'mapa-hidrografia-obres-wms',
 'mapa-orografia-relleu-wms',
 'mapa-parcelari',
 'mapa-peuat',
 'mapa-planol-ciutat-bcn-wms',
 'mapa-serveis-publics-wms',
 'mapa-urbanistic',
 'mapa-usos-sol-wms',
 'mapa-vegetacio-wms',
 'mapa-xarxa-topografica-municipal-wms',
 'mapes-immissio-qualitat-aire',
 'mediambient-contenidorssal',
 'mediambient-puntsrecollidaarbresnadal',
 'mediambient-puntsrobaamiga',
 'mediambient-puntsverdsbarri',
 'mediambient-puntsverdsmobils',
 'mediambient-puntverdcolaborador',
 'mercats-fires-carrer',
 'mercats-municipals',
 'mesures-estacions-meteorologiques',
 'metadades-estacions-meteorologiques',
 'metadades-variables-est-meteo',
 'mobilitat-quotidiana',
 'modificacions-credit-pressupost',
 'modificacions-de-contractes',
 'n-edif-hab-n-immo-edif',
 'n-edif-hab-segons-any-construc',
 'n-edif-hab-segons-estat-cons-edifici',
 'n-edif-hab-segons-instal',
 'n-edif-hab-segons-n-immo',
 'n-edif-hab-segons-nombre-immo',
 'n-edif-hab-segons-nombre-plantes',
 'n-edif-hab-segons-nombre-plantes-sobre-rasant',
 'n-edif-hab-segons-nombre-plantes-sota-rasant',
 'n-edif-hab-segons-n-places-gar',
 'n-edif-hab-segons-n-plantes-sobre-rasant',
 'n-edif-hab-segons-n-plantes-sota-rasant',
 'n-edif-hab-tipus-edif',
 'nomenclator-bcn',
 'notaris_compravendes_trans_tip_us',
 'notaris_compravendes_trans_tip_us_sup',
 'np-asia-dipositsvehicles-bcn',
 'np-circuits-caminar-correr',
 'np-esculleres',
 'np-espais-gimnastica',
 'np-jardins-botanics',
 'np-jardins-interiors-illa',
 'np-molls',
 'np-nasia-diposits-aigues-pluvials',
 'np-nasia-fossars',
 'np-nasia-miradors',
 'np-piscines',
 'np-plantes-depuradores',
 'np-platges',
 'np-quioscs-tramits',
 'np-umbracles',
 'obres',
 'oferta-publica',
 'ordenances-municipals',
 'pad_alt_mdbas',
 'pad_bai_mdbas',
 'pad_cdo_b_barri-des',
 'pad_def_mdbas',
 'pad-dimensions',
 'pad_dom_mdbas_dones',
 'pad_dom_mdbas_edat-0018',
 'pad_dom_mdbas_edat-1864',
 'pad_dom_mdbas_edat-6599',
 'pad_dom_mdbas_homes',
 'pad_dom_mdbas_nacionalitat',
 'pad_dom_mdbas_nacionalitat_edat',
 'pad_dom_mdbas_n-persones',
 'pad_dom_mdbas_tipus-domicili',
 'pad_dom_mdbas_tipus-domicili_edat',
 'pad_emi_mdbas',
 'pad_emi_mdbas_nacionalitat-g',
 'pad_imm_mdbas',
 'pad_imm_mdbas_nacionalitat-g',
 'pad_m_cognom',
 'pad_mdbas',
 'pad_mdbas_edat-1',
 'pad_mdbas_edat-q',
 'pad_mdba_sexe_edat-1',
 'pad_mdba_sexe_edat-q',
 'pad_mdbas_lloc-naix_sexe',
 'pad_mdbas_nacionalitat-continent_sexe',
 'pad_mdbas_nacionalitat-g_sexe',
 'pad_mdbas_niv-educa-esta_sexe',
 'pad_mdbas_sexe',
 'pad_mdb_lloc-naix-continent_edat-q_sexe',
 'pad_mdb_lloc-naix_edat-q_sexe',
 'pad_mdb_lloc-naix-regio_sexe',
 'pad_mdb_nacionalitat-contintent_edat-q_sexe',
 'pad_mdb_nacionalitat-g_edat-q_sexe',
 'pad_mdb_nacionalitat-regio_sexe',
 'pad_mdb_niv-educa-esta_edat-lloc-naix',
 'pad_mdb_niv-educa-esta_edat-q_sexe',
 'pad_m_nom_decada_sexe',
 'pad_m_nom_sexe',
 'pad_nai_mdbas',
 'pad_sol_mdb_sexe_edat-q',
 'parades-de-taxi',
 'patis-escolars',
 'patrimoni-arquitectonic-protegit',
 'pbd-cataleg-continguts',
 'p-cons-inicials-segons-lgep-loepsf',
 'perfil-contractant',
 'piezometres_detall',
 'piezometres_equipaments',
 'plantilla-municipal',
 'plaques-fotovoltaiques',
 'plaques-fotovoltaiques-tipologia',
 'poblacio-exposada-mapa-estrategic-soroll',
 'poblacio_projectada',
 'poblacio-vulnerable',
 'precipitacio-hist-bcn',
 'prediccio-meteorologica-del-barcelones',
 'presencia-absencia-vegetacio',
 'pressupost-despeses',
 'pressupost-ingressos',
 'prorrogues-de-contractes',
 'provisio-promocio',
 'proximitat-espais-verds',
 'punts-ancoratge-bicicletes',
 'punts-critics-neteja-barcelona',
 'punts-informacio-turistica',
 'punts-recarrega-vehicles-electrics',
 'punts-verds',
 'punts-wifi',
 'qualificacions-elements-urbanistics',
 'qualitat-aire-detall-bcn',
 'qualitat-aire-estacions-bcn',
 'rasters-mapa-estrategic-soroll',
 'rebuts-quota-padro-guals',
 'rebuts-quota-padro-iae',
 'rebuts-quota-padro-residus-bcn',
 'rebuts-quota-padro-vehicle-bcn',
 'rebuts-quota-padro-vetlladors-terrasses',
 'recintes-gran-aforament',
 'registre-de-convenis',
 'registre-estudis-i-informes',
 'relacio-contractistes',
 'renda-disponible-llars-bcn',
 'renda-tributaria-per-persona-atlas-distribucio',
 'renda-tributaria-unitat-consum-atlas-distribucio',
 'resums-trimestrals-contractacio',
 'risc-contaminacio-acustica',
 'ronda-verda',
 'sanitat-farmacies',
 'sanitat-hospitals-atencio-primaria',
 'sanitat-serveis-sanitaris',
 'servei-cataleg-metadades-csw',
 'serveissocials-centresdiagentgran',
 'serveissocials-centresserveissocials',
 'serveissocials-equipsatencioinfanciaadolescencia',
 'serveissocials-habitatgestutelats',
 'serveissocials-menjadorssocials',
 'serveissocials-oficinesbenestarsocial',
 'serveissocials-puntsassessoramentenergetic',
 'serveissocials-puntsinformacioiatenciodones',
 'serveissocials-residenciesgentgran',
 'subvencions-a-ens-publics-no-integrats-cercador-post-2019',
 'subvencions-atorgades-ajuntament-i-instituts',
 'subvencions_entitats_nfge',
 'subvencions-i-transferencies-a-ens-publics',
 'subvencions-transferencies-cultura',
 'tanatoris',
 'tarifes-aparcament-superficie',
 'taula-direle',
 'taula-direle-sec-cens',
 'taula-map-illa',
 'taula-segimon',
 'teleferics',
 'temperatures-hist-bcn',
 'terrasses-comercos-vigents',
 'tramer-mapa-estrategic-soroll',
 'trams',
 'trams-aparcament-superficie',
 'transferencies-encomanes-gestio',
 'transitaeri_flightradar_ppal_aeroport',
 'transitaeri_flightradar_ppal_comp_zona',
 'transitaeri_flightradar_ppal_pais',
 'transit-relacio-trams',
 'transit-relacio-trams-per-itinerari',
 'transports',
 'transports-metropolitants-companyies-autocars-de-barcelona',
 'us-del-servei-bicing',
 'viatges-govern-bcn',
 'vies-ciclables',
 'xarxa-refugis-climatics',
 'xarxasoroll-equipsmonitor-dades',
 'xarxasoroll-equipsmonitor-instal',
 'zbe-ambit',
 'zones30-carrers',
 'zones-carrega-descarrega',
 'zones-estacionament-zona-bus']

En primer terme, accedim al llistat de datasets actual a través del metode "/package_list", per a escollir un dataset.

## 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [25]:
bcn_od_url = "https://opendata-ajuntament.barcelona.cat/data/api/action/"
response_agenda = requests.get(f"{bcn_od_url}/package_show?id=agenda-cultural")
try:
    response_agenda.raise_for_status()
except requests.exceptions.HTTPError as e:
        print(f"Error HTTP: {e}")

agenda = response_agenda.json()

agenda

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': 'Activitats culturals de la ciutat de Barcelona classificada per temàtiques.  ',
   'en': 'Cultural activities of the city of Barcelona classified by subject matters. ',
   'es': 'Actividades culturales de la ciudad de Barcelona clasificadas por temáticas.'},
  'geolocation': 'Yes_with_map_view',
  'code': 'AGENDA_CULTURAL',
  'url_tornada': {'ca': 'http://guia.barcelona.cat/agenda',
   'en': 'http://guia.barcelona.cat/en/agenda/',
   'es': 'http://guia.barcelona.cat/es/agenda/'},
  'dataset_fields_description': '__Important:__ A partir del __24/03/2021__  i en relació a canvis en el sistema origen de les dades, es deixa de publicar el recurs en format .xml quedant substituït per el de format .json.',
  'fuente': 'Ajuntament de Barcelona',
  'private': False,
  'num_tags': 2,
  'api': 'Yes',
  'frequency': 'DIARIA',
  'id': '2767159c-1c98-46b8-a686-2b25b40cb053',
  'title_translated': {'ca': 'Agenda cultural de la ciutat de Barcelona',
   'en': 'Cultural Agenda in the city of Barcelona',
   'es': 'Agenda cultural de la ciudad de Barcelona'},
  'metadata_modified': '2023-10-11T11:41:42.630828',
  'author': "Gerència d'Àrea Agenda 2030, Transició Digital i Esports",
  'author_email': '',
  'isopen': True,
  'long_format': 'No',
  'state': 'active',
  'version': '',
  'relationships_as_object': [],
  'department': "Direcció de Serveis d'Informació i Atenció Ciutadana",
  'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
  'type': 'dataset',
  'resources': [{'cache_last_updated': None,
    'token_type': '',
    'package_id': '2767159c-1c98-46b8-a686-2b25b40cb053',
    'datastore_active': True,
    'id': '3abb2414-1ee0-446e-9c25-380e938adb73',
    'size': '3359950',
    'state': 'active',
    'api_access_number': 9873,
    'api_access_number_absolute': 53773,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 1711,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'Yes',
    'file_volum': 'middle',
    'mimetype': None,
    'cache_url': None,
    'name': 'opendatabcn_agenda-cultural-csv.csv',
    'created': '2021-06-10T08:42:44.391483',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/2767159c-1c98-46b8-a686-2b25b40cb053/resource/3abb2414-1ee0-446e-9c25-380e938adb73/download',
    'downloads_absolute': 2628,
    'map_visualization_res': 'data_explorer_map',
    'qa': {'updated': '2026-05-24T02:05:58.939970',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2021-06-11T02:04:32.074598',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': '2021-06-11T06:01:41',
    'position': 0,
    'revision_id': 'b99b8887-b60e-4506-b3b7-bf0ea3cdf0ca',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '2767159c-1c98-46b8-a686-2b25b40cb053',
    'datastore_active': False,
    'id': '59b9c807-f6c1-4c10-ac51-1ace65485079',
    'size': '115303044',
    'state': 'active',
    'api_access_number': 90,
    'api_access_number_absolute': 156,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 2015,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'Yes',
    'file_volum': 'big',
    'mimetype': None,
    'cache_url': None,
    'name': 'opendatabcn_agenda-cultural.json',
    'created': '2021-03-24T14:23:30.329216',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/2767159c-1c98-46b8-a686-2b25b40cb053/resource/59b9c807-f6c1-4c10-ac51-1ace65485079/download',
    'downloads_absolute': 9096,
    'map_visualization_res': 'none',
    'qa': {'updated': '2026-05-24T02:05:58.952765',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2021-03-25T02:04:21.942141',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': '2021-06-11T07:44:33',
    'position': 1,
    'revision_id': 'b99b8887-b60e-4506-b3b7-bf0ea3cdf0ca',
    'resource_type': None}],
  'token_required': 'No',
  'decalatgeNum': 'N/A',
  'tags': [{'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Agenda',
    'id': '9a592892-f5f2-4f59-85c8-f82f39211bcc',
    'name': 'Agenda'},
   {'vocabulary_id': None,
    'state': 'active',
    'display_name': 'Agenda cultural',
    'id': 'a2b0007f-6de1-4ed4-a58c-9be89fbc4beb',
    'name': 'Agenda cultural'}],
  'ODS_Principal_agenda_2030': 'ODS 11: Ciutats i comunitats sostenibles',
  'fecha_publicacion': '2015-11-19',
  'ODS_Colateral2_agenda_2030': 'N/A',
  'ODS_Colateral1_agenda_2030': 'N/A',
  'license_id': 'CC-BY-4.0',
  'hide_url': 'Yes',
  'relationships_as_subject': [],
  'license_title': 'Creative Commons Attribution 4.0',
  'groups': [],
  'num_resources': 2,
  'organization': {'description': '',
   'created': '2017-01-24T16:55:06.041910',
   'title': 'Cultura i oci',
   'name': 'cultura-i-oci',
   'is_organization': True,
   'state': 'active',
   'image_url': 'bcn-icon-cultura',
   'revision_id': '37761928-3e00-4708-9638-ba2d35f9ab9b',
   'type': 'organization',
   'id': 'b66c0300-8771-48ff-8618-cd5452ddb48a',
   'approval_status': 'approved'},
  'name': 'agenda-cultural',
  'url': 'http://www.barcelona.cat',
  'notes': 'Cultural activities of the city of Barcelona classified by subject matters. ',
  'owner_org': 'b66c0300-8771-48ff-8618-cd5452ddb48a',
  'load_type': 'link_extern',
  'qa': {'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.',
   'updated': '2026-05-24T02:05:58.952765',
   'openness_score': 3},
  'tag': 'Agenda,Agenda cultural',
  'license_url': 'https://creativecommons.org/licenses/by/4.0/',
  'historical': 'No',
  'title': 'Cultural Agenda in the city of Barcelona',
  'revision_id': '52312206-3806-44d3-91a8-6554f87686de',
  'extras': [{'key': '*00.', 'value': '__ESTRUCTURA RECURS FORMAT .CSV__'},
   {'key': '*01.',
    'value': "Consultar __'Definició de camps'__ al dataset __[ Miradors a la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/np-nasia-miradors)__"},
   {'key': '00.', 'value': '__ESTRUCTURA RECURS EN FORMAT .JSON__'},
   {'key': '01.',
    'value': "Consultar __'Definició de camps'__ al dataset __[LLista d'esdeveniments diaris de la ciutat de Barcelona](https://opendata-ajuntament.barcelona.cat/data/ca/dataset/agenda-diaria)__  "}]}}

Ente el llistat, trobem agenda-cultural, que disposa de recursos en format .csv. Busquem el resource id que mostra el json del recurs:

"id': '3abb2414-1ee0-446e-9c25-380e938adb73"

## 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [33]:
resource_id = "3abb2414-1ee0-446e-9c25-380e938adb73"

url_search = f"{bcn_od_url}/datastore_search?resource_id={resource_id}&limit=200"

response_search = requests.get(url_search)
response_search.raise_for_status()

data_search = response_search.json()
data_search["result"]["records"]

[{'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': None,
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': '',
  'values_category': '',
  'addresses_zip_code': '',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-23T03:00:00+02:00',
  'addresses_district_name': '',
  'end_date': '2026-10-10T03:00:00',
  'geo_epgs_25831_x': None,
  'addresses_start_street_number': '',
  'register_id': '\ufeff99400654628',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '',
  '_id': 1,
  'name': '"Cicle d\'espectacles i concerts ""Terrats en Cultura"""',
  'addresses_road_id': '',
  'created': '2020-07-06T10:02:55+02:00',
  'geo_epgs_25831_y': None,
  'institution_name': '',
  'modified': '2026-05-15T08:15:50.159055+02:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': None,
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': '',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.1564074948215346',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Gran Via de les Corts Catalanes',
  'values_category': '',
  'addresses_zip_code': '08015',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-20T03:00:00+02:00',
  'addresses_district_name': 'Eixample',
  'end_date': '2026-06-15T03:00:00',
  'geo_epgs_25831_x': '429462.20574299723',
  'addresses_start_street_number': '491',
  'register_id': '\ufeff99400680733',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '02',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '09',
  '_id': 2,
  'name': "Taller 'Urban sketching'",
  'addresses_road_id': '169409',
  'created': '2021-11-30T10:38:19.081158+01:00',
  'geo_epgs_25831_y': '4581379.621529794',
  'institution_name': '',
  'modified': '2026-03-02T15:21:27.162991+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.3808491471351',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': "la Nova Esquerra de l'Eixample",
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.165900883899018',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de València',
  'values_category': '',
  'addresses_zip_code': '08009',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-13T03:00:00+02:00',
  'addresses_district_name': 'Eixample',
  'end_date': '2026-06-15T03:00:00',
  'geo_epgs_25831_x': '430270.6195702426',
  'addresses_start_street_number': '302',
  'register_id': '\ufeff99400680773',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '02',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '07',
  '_id': 3,
  'name': "Taller 'Country line dance'",
  'addresses_road_id': '350308',
  'created': '2021-11-30T11:07:48.112386+01:00',
  'geo_epgs_25831_y': '4582889.5419638995',
  'institution_name': '',
  'modified': '2026-03-10T11:11:24.540789+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.394518975814755',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': "la Dreta de l'Eixample",
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.165900883899018',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de València',
  'values_category': '',
  'addresses_zip_code': '08009',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-14T03:00:00+02:00',
  'addresses_district_name': 'Eixample',
  'end_date': '2026-06-09T03:00:00',
  'geo_epgs_25831_x': '430270.6195702426',
  'addresses_start_street_number': '302',
  'register_id': '\ufeff99400680806',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '02',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '07',
  '_id': 4,
  'name': "Taller 'El món del color: tria la teva tècnica!'",
  'addresses_road_id': '350308',
  'created': '2021-11-30T12:04:05.698755+01:00',
  'geo_epgs_25831_y': '4582889.5419638995',
  'institution_name': '',
  'modified': '2026-03-10T13:00:31.400168+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.394518975814755',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': "la Dreta de l'Eixample",
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.1251516661411447',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'C Major de Sarrià',
  'values_category': '',
  'addresses_zip_code': '08017',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'BARCELONA',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-10-02T03:00:00+02:00',
  'addresses_district_name': 'Sarrià-Sant Gervasi',
  'end_date': '2026-10-12T03:00:00',
  'geo_epgs_25831_x': '426865.6676166989',
  'addresses_start_street_number': '1',
  'register_id': '\ufeff1247124446',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '05',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '23',
  '_id': 5,
  'name': 'Dates de festa major',
  'addresses_road_id': '206505',
  'created': '2001-09-04T00:00:00+02:00',
  'geo_epgs_25831_y': '4583086.730320991',
  'institution_name': '',
  'modified': '2026-04-10T13:44:48.834590+02:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.39599253027976',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Sarrià',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.173233437180801',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Passeig de Fabra i Puig',
  'values_category': '',
  'addresses_zip_code': '08031',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-22T03:00:00+02:00',
  'addresses_district_name': 'Nou Barris',
  'end_date': '2026-06-04T03:00:00',
  'geo_epgs_25831_x': '430921.7324244287',
  'addresses_start_street_number': '274',
  'register_id': '\ufeff99400682703',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '08',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '46',
  '_id': 6,
  'name': "Taller 'Fotografia - Nivell 2'",
  'addresses_road_id': '119003',
  'created': '2021-12-27T09:53:40.532335+01:00',
  'geo_epgs_25831_y': '4586876.849222638',
  'institution_name': '',
  'modified': '2026-03-26T14:11:02.394860+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.4304874584176',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'el Turó de la Peira',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '16',
  'geo_epgs_4326_lon': '41.415085655472545',
  'values_attribute_name': '',
  'estimated_dates': '2.1027779676430014',
  'addresses_road_name': "Carrer d'Elisa Moragas i Badia",
  'values_category': '',
  'addresses_zip_code': 'Sarrià-Sant Gervasi',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': '08017',
  'secondary_filters_name': '',
  'timetable': '2026-09-20T03:00:00',
  'secondary_filters_tree': '',
  'start_date': '',
  'addresses_district_name': '05',
  'end_date': '2026-09-10T03:00:00',
  'geo_epgs_25831_x': None,
  'addresses_start_street_number': '16',
  'register_id': '\ufeff1136111323',
  'institution_id': '',
  'addresses_main_address': 'Barcelona',
  'addresses_district_id': ' el Tibidabo i les Planes"',
  'addresses_roadtype_id': None,
  'addresses_type': 'True',
  'addresses_neighborhood_id': '22',
  '_id': 7,
  'name': '"""Festa Major de Vallvidrera"""',
  'addresses_road_id': '280803',
  'created': '2001-05-16T00:00:00+02:00',
  'geo_epgs_25831_y': '425017.239',
  'institution_name': '',
  'modified': '2026-04-10T13:43:49.263784+02:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '4585225.559',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': '"Vallvidrera',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '9',
  'geo_epgs_4326_lon': '2.192288054869178',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de la Conreria',
  'values_category': '',
  'addresses_zip_code': '08003',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-14T03:00:00+02:00',
  'addresses_district_name': 'Ciutat Vella',
  'end_date': '2026-06-09T03:00:00',
  'geo_epgs_25831_x': '432461.81799999997',
  'addresses_start_street_number': '1',
  'register_id': '\ufeff99400688059',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '01',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '03',
  '_id': 8,
  'name': "Taller 'Impro teatre'",
  'addresses_road_id': '088908',
  'created': '2022-03-21T11:59:45.290049+01:00',
  'geo_epgs_25831_y': '4581286.54',
  'institution_name': '',
  'modified': '2026-03-03T11:52:34.108486+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.38026816937648',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'la Barceloneta',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '9',
  'geo_epgs_4326_lon': '2.192288054869178',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de la Conreria',
  'values_category': '',
  'addresses_zip_code': '08003',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-15T03:00:00+02:00',
  'addresses_district_name': 'Ciutat Vella',
  'end_date': '2026-06-10T03:00:00',
  'geo_epgs_25831_x': '432461.81799999997',
  'addresses_start_street_number': '1',
  'register_id': '\ufeff99400688090',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '01',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '03',
  '_id': 9,
  'name': "Taller 'Fem barri: Intel·ligència artificial'",
  'addresses_road_id': '088908',
  'created': '2022-03-21T14:17:10.770410+01:00',
  'geo_epgs_25831_y': '4581286.54',
  'institution_name': '',
  'modified': '2026-03-03T12:32:04.189046+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.38026816937648',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'la Barceloneta',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.160723502038599',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Feliu i Codina',
  'values_category': '',
  'addresses_zip_code': '08031',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-14T03:00:00+02:00',
  'addresses_district_name': 'Horta-Guinardó',
  'end_date': '2026-06-09T03:00:00',
  'geo_epgs_25831_x': '429878.96649043774',
  'addresses_start_street_number': '20',
  'register_id': '\ufeff99400673637',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '07',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '43',
  '_id': 10,
  'name': "Taller 'Swing solo'",
  'addresses_road_id': '122303',
  'created': '2021-07-29T09:45:40.089025+02:00',
  'geo_epgs_25831_y': '4587142.492419921',
  'institution_name': '',
  'modified': '2026-02-25T17:50:51.306229+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.43278963946825',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Horta',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.1184352989192647',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Av Diagonal',
  'values_category': '',
  'addresses_zip_code': '08034',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'BARCELONA',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-06-26T03:00:00+02:00',
  'addresses_district_name': 'Les Corts',
  'end_date': '2026-07-21T03:00:00',
  'geo_epgs_25831_x': '426293.53040473606',
  'addresses_start_street_number': '686',
  'register_id': '\ufeff99400336505',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '04',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '21',
  '_id': 11,
  'name': '"Festival ""Les Nits Occident"" als Jardins del Palau de Pedralbes"',
  'addresses_road_id': '144601',
  'created': '2014-02-28T11:32:32+01:00',
  'geo_epgs_25831_y': '4582044.054369566',
  'institution_name': '',
  'modified': '2026-05-12T11:19:28.453206+02:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.38654937434819',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Pedralbes',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.184931573020558',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Las Navas de Tolosa',
  'values_category': '',
  'addresses_zip_code': '08027',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-13T03:00:00+02:00',
  'addresses_district_name': 'Sant Andreu',
  'end_date': '2026-06-22T03:00:00',
  'geo_epgs_25831_x': '431884.9903809375',
  'addresses_start_street_number': '312',
  'register_id': '\ufeff99400337053',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '09',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '63',
  '_id': 12,
  'name': "Taller 'Ioga - relaxació'",
  'addresses_road_id': '226400',
  'created': '2014-03-10T15:41:50+01:00',
  'geo_epgs_25831_y': '4585363.553166486',
  'institution_name': '',
  'modified': '2026-03-11T14:23:39.680817+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.41693998158291',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Navas',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '',
  'geo_epgs_4326_lon': '2.1246720318706647',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Jaume Piquet',
  'values_category': '',
  'addresses_zip_code': '08017',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-06-30T03:00:00+02:00',
  'addresses_district_name': 'Sarrià-Sant Gervasi',
  'end_date': '2026-07-14T03:00:00',
  'geo_epgs_25831_x': '426828.2269232857',
  'addresses_start_street_number': '23',
  'register_id': '\ufeff99400683052',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '05',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '23',
  '_id': 13,
  'name': "Taller 'Protectors solars: salut de la pell i impacte ambiental'",
  'addresses_road_id': '165805',
  'created': '2022-01-06T14:03:30.125953+01:00',
  'geo_epgs_25831_y': '4583349.96874513',
  'institution_name': '',
  'modified': '2026-05-21T10:14:14.129483+02:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.3983599977031',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Sarrià',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '10',
  'geo_epgs_4326_lon': '2.200290194498161',
  'values_attribute_name': '',
  'estimated_dates': '',
  'addresses_road_name': 'Carrer de Quito',
  'values_category': '',
  'addresses_zip_code': '08030',
  'secondary_filters_id': '',
  'values_value': '',
  'addresses_town': 'Barcelona',
  'secondary_filters_name': '',
  'timetable': None,
  'secondary_filters_tree': '',
  'start_date': '2026-04-14T03:00:00+02:00',
  'addresses_district_name': 'Sant Andreu',
  'end_date': '2026-06-09T03:00:00',
  'geo_epgs_25831_x': '433198.615',
  'addresses_start_street_number': '8',
  'register_id': '\ufeff99400683083',
  'institution_id': '',
  'addresses_main_address': 'True',
  'addresses_district_id': '09',
  'addresses_roadtype_id': None,
  'addresses_type': '',
  'addresses_neighborhood_id': '58',
  '_id': 14,
  'name': "Taller 'La cuina de Baró'",
  'addresses_road_id': '273003',
  'created': '2022-01-07T10:46:55.193185+01:00',
  'geo_epgs_25831_y': '4588610.205',
  'institution_name': '',
  'modified': '2026-03-19T09:48:10.226775+01:00',
  'secondary_filters_asia_id': '',
  'secondary_filters_fullpath': '',
  'geo_epgs_4326_lat': '41.4462918208594',
  'values_description': '',
  'values_id': '',
  'addresses_neighborhood_name': 'Baró de Viver',
  'values_outstanding': '',
  'values_attribute_id': ''},
 {'addresses_roadtype_name': None,
  'addresses_end_street_number': '321',
  'geo_epgs_4326_lon': '41.405576512012246',
  'values_attribute_name': '',
  'estimated_dates': '2.167687591797475',
  'addresses_road_name': '325005',
  'values_category': '',

Configurem la cerca amb l'ID del dataset i hi posem un limit de 200, en observar que el resultat conté molts camps buits, per tal de poder tenir una major visió del tipus de dades que trobarem en aquest dataset. 

Desprès en filtrem els resultats per a confeccionar el DataFrame i posteriorment, exportar com a CSV.

## 4. Converteix els resultats a un DataFrame.

In [31]:
df = pd.DataFrame(data_search["result"]["records"])
df

,addresses_roadtype_name,addresses_end_street_number,geo_epgs_4326_lon,values_attribute_name,estimated_dates,addresses_road_name,values_category,addresses_zip_code,secondary_filters_id,values_value,...,institution_name,modified,secondary_filters_asia_id,secondary_filters_fullpath,geo_epgs_4326_lat,values_description,values_id,addresses_neighborhood_name,values_outstanding,values_attribute_id
0,None,,None,,,,,,,,...,,2026-05-15T08:15:50.159055+02:00,,,None,,,,,
1,None,,2.1564074948215346,,,Gran Via de les Corts Catalanes,,08015,,,...,,2026-03-02T15:21:27.162991+01:00,,,41.3808491471351,,,la Nova Esquerra de l'Eixample,,
2,None,,2.165900883899018,,,Carrer de València,,08009,,,...,,2026-03-10T11:11:24.540789+01:00,,,41.394518975814755,,,la Dreta de l'Eixample,,
3,None,,2.165900883899018,,,Carrer de València,,08009,,,...,,2026-03-10T13:00:31.400168+01:00,,,41.394518975814755,,,la Dreta de l'Eixample,,
4,None,,2.1251516661411447,,,C Major de Sarrià,,08017,,,...,,2026-04-10T13:44:48.834590+02:00,,,41.39599253027976,,,Sarrià,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,None,,2.182465058010549,,,Plaça de Fort Pienc,,08013,,,...,,2026-03-05T09:46:16.925616+01:00,,,41.39558658720727,,,el Fort Pienc,,
96,None,,2.184931573020558,,,Carrer de Las Navas de Tolosa,,08027,,,...,,2026-03-12T14:53:22.614247+01:00,,,41.41693998158291,,,Navas,,
97,None,,2.182465058010549,,,Plaça de Fort Pienc,,08013,,,...,,2026-03-05T10:49:35.710589+01:00,,,41.39558658720727,,,el Fort Pienc,,
98,None,2,4582085.127,20055,41.387339989243294,301506,612577,01,False,Telèfons,...,,2024-07-01T12:03:10.425706+02:00,,,431037.525,932 957 207,True,04,Venda d'entrades,
99,2026-04-13T13:45:20.297608,Carrer de Martí Molins,4586141.181659135,20006,41.42397425702554,,716095,09,False,Telèfons,...,"amb Montse Pérez""",,,,432244.9097293351,93 351 17 02,True,,Informació,

## 5. Desa el DataFrame en un fitxer .csv.

In [34]:
df.to_csv("agenda_cultural.csv")